### ISSUE TITLE
XML File Usage

### ISSUE THREAD

**Issue by jmschonfeld** [StateFarmInsCodingCompetition/2018-StateFarm-CodingCompetitionProblem#1]
Hi, two quick questions:

1. Should we be using the `small-metro.xml` and `large-metro.xml` in `src/main/resources` or `src/test/resources`? (or are they the same?)
2. Currently all of the JUnits pass in file paths such as `/small-metro.xml` indicating the xml file should be in the root folder of the computer. Should we assume that when our code is tested the file will indeed exist in the root folder of the computer?

**Comment by trippinBilly1979** [comment]
1) They are identical.. 

2) Do not assume that the file will exist in the root of the computer.  In your implementation do not assume that the preceding / indicates the root of the filesystem.
