### ISSUE TITLE
Missing @Test annotation

### ISSUE THREAD

**Issue by aberamseyer** [StateFarmInsCodingCompetition/2018-StateFarm-CodingCompetitionProblem#3]
https://github.com/StateFarmInsCodingCompetition/2018-StateFarm-CodingCompetitionProblem/blob/683739008e610db1d517bbe72616f76f3d9fcfa9/src/test/java/com/codingcompetition/statefarm/StreetMapDataInterpreterTest.java#L53
Is there supposed to be an annotation here to trigger the test? There are no other usages of this method in the code.

**Comment by trippinBilly1979** [comment]
Nice Catch!!!   

Yes was intended to be a test case..  I have pushed an update to master for the @Test annotation.   Feel free to pull it in if you'd like ...   I believe we'll be sending something out to the other participants letting them know
